In [0]:
import numpy as np
import pandas as pd
import matplotlib

In [0]:
from google.colab import files
uploaded = files.upload()

Saving hotel_bookings.csv to hotel_bookings.csv

In [0]:
import io
df = pd.read_csv(io.BytesIO(uploaded['hotel_bookings.csv']))

In [0]:
pd.options.display.max_columns = None

In [0]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [0]:
df.groupby(['hotel']).mean()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
hotel,,,,,,,,,,,,,,,,,,,,
City Hotel,0.417270,109.735724,2016.174285,27.177449,15.786625,0.795185,2.182957,1.850977,0.091370,0.004941,0.025615,0.079743,0.132371,0.187369,28.144721,145.271618,3.226774,105.304465,0.024367,0.546918
Resort Hotel,0.277634,92.675686,2016.121443,27.140864,15.821243,1.189815,3.128732,1.867149,0.128682,0.013904,0.044383,0.101722,0.146455,0.287968,217.571725,241.486165,0.527758,94.952930,0.138068,0.619770

In [0]:
df.groupby(['arrival_date_month']).mean()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
arrival_date_month,,,,,,,,,,,,,,,,,,,,
April,0.407972,94.822888,2016.510506,15.997114,16.309135,0.948688,2.418162,1.876274,0.102895,0.004780,0.025521,0.042565,0.128686,0.225719,89.899877,225.310403,3.012445,100.380790,0.057084,0.521508
August,0.377531,121.137710,2016.074656,33.422570,15.690855,1.060460,2.836420,2.002955,0.200389,0.014124,0.016070,0.068314,0.055776,0.264755,87.293802,99.510417,0.398717,140.111523,0.072062,0.736687
December,0.349705,73.561357,2015.569322,51.097345,16.050442,0.865044,2.357522,1.826254,0.108555,0.011504,0.046313,0.093068,0.185251,0.235398,90.395312,155.735135,3.007522,81.076776,0.074041,0.614012
February,0.334160,47.859569,2016.517724,7.411378,15.750000,0.853123,2.177987,1.791026,0.097918,0.007313,0.050942,0.075235,0.176872,0.191869,86.983594,210.817814,0.764874,73.582276,0.063089,0.525657
January,0.304773,45.310002,2016.620847,2.987182,16.117389,0.779389,2.192107,1.690673,0.076235,0.008096,0.066959,0.089391,0.304773,0.247765,101.446636,170.411874,2.526396,70.361241,0.082813,0.547478
July,0.374536,136.322565,2016.200379,28.997157,16.110418,1.120291,2.805545,1.987521,0.183398,0.009557,0.023774,0.116578,0.126372,0.217676,89.984230,161.166667,0.229919,126.788013,0.068636,0.671748
June,0.414572,128.247280,2016.516226,24.555535,15.119298,0.920377,2.655453,1.860591,0.096627,0.006491,0.025779,0.021574,0.155682,0.192248,90.604018,197.758701,1.955115,116.672192,0.055672,0.563946
March,0.321523,70.119257,2016.507454,11.590259,16.335205,0.858689,2.560649,1.804676,0.071472,0.005820,0.043496,0.027159,0.184399,0.221871,88.777273,216.677155,1.376965,80.679646,0.061568,0.497447
May,0.396658,117.646171,2016.535408,20.270206,16.029260,0.869646,2.406921,1.826732,0.071665,0.006106,0.031041,0.018319,0.155288,0.217200,88.945584,186.977833,4.339072,108.695516,0.052074,0.532610
November,0.312334,76.580807,2015.655578,46.657345,14.432146,0.785105,2.404033,1.690904,0.041066,0.006623,0.043126,0.038711,0.159553,0.248749,97.190793,201.553137,1.767736,73.794962,0.067265,0.581248
October,0.380466,122.994624,2015.555824,42.344086,15.467832,0.895341,2.230735,1.817115,0.062993,0.005556,0.028047,0.153943,0.077867,0.202061,73.066061,190.506365,4.598835,87.908879,0.056452,0.494265
September,0.391702,136.675200,2015.513323,38.093833,15.900266,0.942044,2.524362,1.872954,0.056909,0.008279,0.019128,0.289113,0.074610,0.197183,68.357635,163.493014,4.221926,105.049657,0.052056,0.501332

In [0]:
df.groupby(['market_segment']).mean()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
market_segment,,,,,,,,,,,,,,,,,,,,
Aviation,0.219409,4.443038,2016.464135,25.088608,15.708861,1.092827,2.514768,1.004219,0.000000,0.000000,0.270042,0.054852,0.430380,0.261603,153.000000,153.000000,0.000000,100.142110,0.025316,0.113924
Complementary,0.130552,13.286676,2016.065949,28.464334,15.417227,0.351279,1.296097,1.485868,0.082100,0.029610,0.309556,0.218035,2.052490,0.332436,99.893204,76.354633,0.052490,2.886366,0.113055,0.932705
Corporate,0.187347,22.125590,2016.073843,26.048725,15.715958,0.438338,1.654580,1.236072,0.010009,0.003022,0.278376,0.167705,2.058546,0.307271,204.907275,171.884590,0.154674,69.358952,0.111992,0.229839
Direct,0.153419,49.859115,2016.183643,26.492623,15.906790,0.856180,2.349595,1.875694,0.178342,0.022926,0.063145,0.018483,0.137157,0.395764,118.838612,260.298077,0.040536,115.445175,0.168253,0.576075
Groups,0.610620,186.973096,2015.987583,27.255666,16.030539,0.788754,2.203776,1.796881,0.002928,0.000656,0.013629,0.273989,0.015951,0.211802,75.098959,258.665708,6.403160,79.479472,0.014235,0.087174
Offline TA/TO,0.343160,135.004459,2015.982989,29.010033,15.607540,1.053512,2.850365,1.819233,0.026962,0.007350,0.015649,0.114373,0.023081,0.161402,88.448426,294.764151,6.142739,87.354783,0.022875,0.268013
Online TA,0.367211,82.998725,2016.291906,26.588540,15.787825,0.991023,2.582963,1.955504,0.165203,0.007631,0.010571,0.016060,0.021903,0.201321,83.874325,171.083333,0.002284,117.197063,0.067709,0.899393
Undefined,1.000000,1.500000,2015.000000,32.000000,4.000000,0.500000,1.000000,2.500000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,15.000000,0.000000,1.500000

In [0]:
df.groupby(['distribution_channel']).mean()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
distribution_channel,,,,,,,,,,,,,,,,,,,,
Corporate,0.220758,44.910289,2016.068444,27.610753,15.307473,0.570616,1.810094,1.320353,0.008836,0.003145,0.235435,0.277670,1.723529,0.364086,214.285714,179.038560,0.190654,69.325204,0.104538,0.205781
Direct,0.174599,57.829362,2016.155411,26.583202,16.082622,0.830044,2.364288,1.844589,0.157323,0.021304,0.063981,0.027586,0.187095,0.398293,125.465385,181.068408,0.626972,106.654983,0.154251,0.534175
GDS,0.191710,20.715026,2016.450777,25.818653,15.549223,0.590674,1.367876,1.088083,0.000000,0.000000,0.015544,0.000000,0.010363,0.093264,193.293194,417.000000,0.000000,120.554301,0.000000,0.196891
TA/TO,0.410259,115.122438,2016.162215,27.224298,15.790150,0.967212,2.569981,1.896240,0.102575,0.006294,0.013262,0.083202,0.021641,0.185123,82.078118,253.462046,2.724706,103.292866,0.046041,0.602565
Undefined,0.800000,23.000000,2015.000000,31.400000,6.200000,1.000000,2.400000,2.200000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.500000,NaN,0.000000,46.240000,0.200000,1.400000

In [0]:
df.groupby(['reserved_room_type']).mean()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
reserved_room_type,,,,,,,,,,,,,,,,,,,,
A,0.391074,110.940240,2016.114380,27.237924,15.704758,0.834826,2.289788,1.781101,0.034595,0.005640,0.035735,0.114392,0.160860,0.202654,74.915824,187.553057,3.119206,90.796658,0.046050,0.493825
B,0.329159,113.268336,2015.962433,28.212880,16.425760,0.958855,2.437388,1.569767,0.552962,0.012522,0.011628,0.049195,0.055456,0.517889,13.004024,68.750000,0.576029,90.360447,0.040250,0.775492
C,0.330472,80.173820,2016.330472,27.974249,15.918455,1.297210,3.372318,2.039700,1.271459,0.070815,0.028970,0.008584,0.030043,0.493562,236.192157,290.000000,0.153433,160.216792,0.190987,0.777897
D,0.317796,86.829488,2016.281652,26.848185,15.929275,1.141347,2.991511,2.088902,0.040727,0.009375,0.019218,0.014687,0.055310,0.216968,88.835423,207.171843,0.249987,120.682882,0.068278,0.779074
E,0.292884,91.121500,2016.267483,26.708646,16.207498,1.310176,3.409793,1.980260,0.091813,0.012854,0.028309,0.019893,0.138791,0.286611,177.541080,195.260000,0.482020,124.540179,0.154093,0.834277
F,0.303763,68.529168,2016.250259,27.393511,16.227132,1.039696,2.678633,1.992406,1.030376,0.015878,0.022782,0.012081,0.072489,0.338281,90.046475,118.300000,0.000000,167.689651,0.131861,0.736969
G,0.364374,80.248329,2016.275549,26.948424,16.116046,1.202961,3.092168,2.077841,1.275549,0.031041,0.031041,0.023878,0.122254,0.341452,195.685809,159.263158,0.072588,175.996027,0.197230,0.654728
H,0.407654,78.387687,2016.217970,28.186356,16.153078,1.101498,2.928453,2.712146,0.980033,0.014975,0.019967,0.004992,0.013311,0.332779,242.709738,343.750000,0.000000,188.223111,0.279534,0.399334
L,0.333333,0.000000,2015.000000,29.833333,10.833333,0.166667,1.000000,2.166667,0.000000,0.000000,0.000000,0.166667,0.333333,0.000000,NaN,NaN,0.000000,124.666667,0.000000,0.000000
P,1.000000,0.000000,2016.500000,31.416667,11.083333,0.333333,0.916667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,300.100000,0.000000,0.000000,0.000000,0.000000

In [0]:
df.groupby(['deposit_type']).mean()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
deposit_type,,,,,,,,,,,,,,,,,,,,
No Deposit,0.283770,88.756615,2016.174014,27.135310,15.814652,0.970165,2.556799,1.862597,0.118400,0.009069,0.035760,0.042039,0.154911,0.249634,90.996175,189.496772,1.519347,103.525067,0.071129,0.651427
Non Refund,0.993624,212.908891,2016.031466,27.448619,15.595462,0.621718,2.091109,1.811407,0.000617,0.000000,0.004387,0.411462,0.010626,0.012477,55.248165,179.189723,7.992253,89.964017,0.000069,0.001782
Refundable,0.222222,152.098765,2016.141975,20.932099,23.456790,0.975309,2.851852,1.907407,0.030864,0.000000,0.024691,0.000000,0.018519,0.592593,189.625000,227.936842,9.586420,76.209753,0.123457,0.141975

In [0]:
df.groupby(['customer_type']).mean()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
customer_type,,,,,,,,,,,,,,,,,,,,
Contract,0.309617,142.969823,2015.510304,33.702159,15.236261,1.469578,3.851079,1.919529,0.065505,0.007851,0.008096,0.225466,0.004171,0.119725,57.529412,27.600000,0.039500,87.549637,0.033121,0.728901
Group,0.102253,55.057192,2016.045061,29.433276,15.603120,0.824957,2.057192,2.346620,0.065858,0.008666,0.279029,0.036395,0.594454,0.294627,109.058577,235.897959,0.369151,83.488579,0.088388,0.644714
Transient,0.407463,93.295515,2016.249517,26.541350,15.795164,0.938815,2.508330,1.886791,0.125975,0.009162,0.034292,0.074208,0.163458,0.187863,86.818050,159.383911,1.316874,107.013621,0.071865,0.631582
Transient-Party,0.254299,137.037056,2015.932375,28.277623,15.904872,0.802022,2.262697,1.726516,0.032205,0.003622,0.021613,0.111885,0.054132,0.354522,91.449406,236.583173,6.318222,86.084253,0.033355,0.329327

In [0]:
df.groupby(['reservation_status']).mean()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
reservation_status,,,,,,,,,,,,,,,,,,,,
Canceled,1.0,147.308622,2016.173094,27.402864,15.692656,0.920497,2.560453,1.908432,0.106177,0.003743,0.011786,0.214032,0.022596,0.094567,75.214003,184.885636,3.664086,105.205241,0.0000,0.323105
Check-Out,0.0,79.984687,2016.147514,27.080143,15.839529,0.928971,2.464053,1.829737,0.102347,0.010377,0.043344,0.015792,0.202977,0.293364,94.055794,190.519265,1.589868,99.987693,0.0993,0.714060
No-Show,1.0,57.182270,2016.130075,23.989229,16.990058,1.095278,2.613919,1.662800,0.118476,0.006628,0.037283,0.005800,0.115162,0.232809,73.848455,166.479592,0.000000,96.378459,0.0000,0.532726